version: 2

node_unit_tests: &node_unit_tests
  steps:
    - checkout
    - run:
        name: Create Checksum
        command: sh .circleci/checksum.sh /tmp/checksums.txt
    - restore_cache:
        keys:
          - npm-cache-{{ checksum "/tmp/checksums.txt" }}
    - run:
        name: Install Dependencies
        command: yarn install
    - save_cache:
        key: npm-cache-{{ checksum "/tmp/checksums.txt" }}
        paths:
          - ./node_modules
          - ./yarn.lock
          - ./packages/*/node_modules
          - ./packages/*/yarn.lock
    - run:
        name: Compile code
        command: yarn compile
    - run:
        name: Unit tests
        command: yarn test
    - run:
        name: report coverage
        command: yarn codecov

browsers_unit_tests: &browsers_unit_tests
  steps:
    - checkout
    - run:
        name: Install Dependencies
        command: yarn install
    - run:
        name: Compile code
        command: yarn compile
    - run:
        name: Unit tests
        command: yarn test:browser
    - run:
        name: report coverage
        command: yarn codecov:browser

jobs:
  lint:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          name: Install modules and dependencies.
          command: yarn install
      - run:
          name: Check code style and linting
          command: yarn run check
  docs:
    docker:
      - image: node:12
    steps:
      - checkout
      - run:
          name: Install modules and dependencies.
          command: yarn install
      - run:
          name: Docs tests
          command: yarn docs-test
      - persist_to_workspace:
          root: packages/opentelemetry-types/docs
          paths: out
  docs-deploy:
    docker:
      - image: node:12
    steps:
      - checkout
      - attach_workspace:
        at: packages/opentelemetry-types/docs
      - run:
        name: Install and configure dependencies
        command: |
          npm install -g --silent gh-pages@2.0.1
          git config user.email dyladan@users.noreply.github.com
          git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "08:7b:ae:2d:8f:dd:a7:4e:ad:f6:44:cc:99:55:34:a1"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist packages/opentelemetry-types/docs/out
  node8:
    docker:
      - image: node:8
    <<: *node_unit_tests
  node10:
    docker:
      - image: node:10
    <<: *node_unit_tests
  node11:
    docker:
      - image: node:11
    <<: *node_unit_tests
  node12:
    docker:
      - image: node:12
    <<: *node_unit_tests
  node12-browsers:
    docker:
      - image: circleci/node:12-browsers
    <<: *browsers_unit_tests

workflows:
  version: 2
  build:
    jobs:
      - lint
      - docs
      - docs-deploy:
        requires:
          - docs
        filters:
          branches:
            only: master
      - node8
      - node10
      - node11
      - node12
      - node12-browsers
